spring.datasource.url=jdbc:h2:mem:petshopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
``

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.dd

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa

spring.datasource.driverClassName=org.h2.Driver
spring.datasource

spring.datasource.driverClassName=org.h2.Driver
spring

spring.datasource.driverClassName=org.h2

spring.datasource.driverClassName=

spring.datasource
